### PR TITLE
Reworked zh_cn translation

### PR DESCRIPTION
**Pull request by HfSrJun**
zh_cn translation of this mod is in bad quality and missing some contents, so I renewed it last year, and now I am PRing it to github.
This translation has already accepted by GTNH's fork of OC, and passed the strict review from the Chinese translation team of GTNH, so don't worry about the quality. I also uploaded it to CFPA(the biggest 3rd-party mc mod translation community in China), but it is still under reviewing by now (because of the lack of reviewers).
Further more, I finished most of the Chinese translation of official wiki.

### CODE REVIEW

**Review by HfSrJun — COMMENTED** [review]
I only uploaded files for 1.12.2, please copy them to other versions like 1.7.10, I believe nothing changed between these to versions (but sticky piston upgrade?)
If files for 1.7.10 is also needed please comment, I will start another PR.

**Comment by mckuhei** [comment]
Good job

**Comment by asiekierka** [comment]
I merged it, but it appears GT:NH uses a different translation upstream. Our 1.7.10 documentation/language files differ to some extent (for example, all the language key names are different, all the filenames are different due to post-1.7 engine changes, some text is also different); this means I can't easily adapt this back to 1.7.10.

As such, I've reverted it and would like to see a 1.7.10 pull request as well if this is to be merged; note, however, that the mod is not exactly maintained anymore (beyond urgent fixes)...

**Comment by HfSrJun** [comment]
> I merged it, but it appears GT:NH uses a different translation upstream. Our 1.7.10 documentation/language files differ to some extent (for example, all the language key names are different, all the filenames are different due to post-1.7 engine changes, some text is also different); this means I can't easily adapt this back to 1.7.10.
> 
> As such, I've reverted it and would like to see a 1.7.10 pull request as well if this is to be merged; note, however, that the mod is not exactly maintained anymore (beyond urgent fixes)...

Actually I do noticed the difference between GTNH port and the official stream, and handled them properly. I will make a new PR the satisfy the 1.7.10 formation, do I need PR the 1.12.2 version again? Please let me know.

**Comment by asiekierka** [comment]
You don't. But I can't promise it will be merged soon; as I said, I only spin new OpenComputers versions when new security issues arise these days...

**Comment by HfSrJun** [comment]
> You don't. But I can't promise it will be merged soon; as I said, I only spin new OpenComputers versions when new security issues arise these days...

1.7.10 PR had submitted(#3737), and I resubmitted the 1.12.2 one in order to fix some minor mistakes and make updating easier(with out revert, just merge #3738). Please merge them when next update coming.

**Pull request merged**
