### PR TITLE
Function to get the itemstacks friendly name

### PR DESCRIPTION
**Pull request by KJA1582**
Comment sais it already, but maybe you do find it useful.

### CODE REVIEW

**Comment by fnuecke** [comment]
Just use `getItemStack().label`.

**Comment by KJA1582** [comment]
That exists??

**Comment by fnuecke** [comment]
Yes. [ItemStacks](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/scala/li/cil/oc/integration/vanilla/ConverterItemStack.scala) and [a few other common Minecraft types](https://github.com/MightyPirates/OpenComputers/tree/master-MC1.7.10/src/main/scala/li/cil/oc/integration/vanilla) have built-in converters that will convert them to maps (i.e. tables in Lua).

**Comment by KJA1582** [comment]
Nice. Thats gonna make my build way smaller in its footprint.

Thanks for the insight, I'm actually learning how to mod Minecraft, so this helps.

**Comment by fnuecke** [comment]
Happy to help!

**Comment by KJA1582** [comment]
On a side note, why did you use Scala and not java? I'm new to both so I have to learn it anyways.

**Comment by fnuecke** [comment]
Because I wanted to learn Scala, really. Also because I like the power it provides (allowing to write code much more concisely, though some might argue it makes it harder to read; IMHO it's just a matter of getting used to it / functional programming in general).

**Comment by KJA1582** [comment]
Talking about hard to read, I come from Objective C. The Syntax is so different, it's like learning to read all over again.

**Pull request closed without merging**
