### PR TITLE
Update fr_FR.lang

### PR DESCRIPTION
**Pull request by ff66theone**
Updated translations for french :
<li>Modified some terms that weren't the same in some places</li>
<li> Deleted spelling mistakes </li>

### CODE REVIEW

**Comment by asiekierka** [comment]
I don't think the temperature values belong in this PR...?

**Comment by ff66theone** [comment]
Yep ! its another work.

**Comment by ff66theone** [comment]
I did the PR before the two commits

**Comment by PublicVoidUpdate** [comment]
Remember kids, if you are running out of space, make sure to delete the french lsnguage pack with 'sudo rm -fr /'!

(Dont do this)

**Comment by ff66theone** [comment]
I reverted changes so there's just the locale update

**Pull request merged**
