### PR TITLE
Updated JEI integration.

### PR DESCRIPTION
**Pull request by Vexatos**
Not sure if this should be merged. Added a version dependency or we would probably have the same problems as the highlighting PR had, with people not updating JEI and reporting crashes.

### CODE REVIEW

**Comment by fnuecke** [comment]
What exactly were those crashes? Did an interface change? If it's just added/removed methods, a good way to stay compatible with both is to just have the union of the interfaces of different versions and omit the `override` on the implementations, IIRC.

**Comment by Vexatos** [comment]
`override` doesn't even matter, it doesn't exist once you're past the compiler IIRC.

**Comment by Vexatos** [comment]
`override` doesn't even matter, it doesn't exist once you're past the compiler IIRC. `IIngredients`, however, is a completely new class.
Updating JEI is required to launch Minecraft with #2134 merged as EnderIO requires it. Unless I change that to use `provided`, which can, of course, be done.

**Comment by fnuecke** [comment]
It's a compile-time thing, yes. But if some signature changed and Optional.Method and/or Injectable.Interface won't help, sure, let's require the new version. Makes sense anyway IMHO :P

**Review by fnuecke — APPROVED** [review]
And I just noticed that fancy new button there...

**Comment by fnuecke** [comment]
Interesting, so that's what that does!

**Pull request merged**
