### PR TITLE
fix term ctrl key (regression), fix grep display

### PR DESCRIPTION
**Pull request by payonel**
1. fix filename display in recursive grep results, it is now correctly showing the relative path, no longer the absolute path
2. fix highlighting multiple grep results in a single line
3. fix showing grep results for --match-only where there are multiple matches per line
4. fix crash when using control+key in term.read() This was a regression caused by a recent update to support ctrl+movement for word jumping

### CODE REVIEW

**Comment by payonel** [comment]
added commit to fix two more term issues
1. fix crash for tty writes that occur during boot before term isAvailable
2. fix crash in term when resolution is set smaller

**Comment by payonel** [comment]
@fnuecke i just realized this resize fix will only work to shrink the terminal window, not enlarge it. I'll amend the 2nd commit to this PR later.

**Comment by payonel** [comment]
@fnuecke this PR is now in a great state. term crash and resize issues resolved, grep fixed too

**Comment by fnuecke** [comment]
Thanks again!

**Pull request merged**
