### PR TITLE
Update robot.names

### PR DESCRIPTION
**Pull request by jecowa**
suggesting some more robot names

### CODE REVIEW

**Comment by Vexatos** [comment]
Robbie AND Robby? I don't think that's legit.

**Comment by fnuecke** [comment]
While I do appreciate the "source" annotations, that makes the file incredibly cluttered. I think I'll adjust the parser to allow for inline comments (e.g. `AdventureCore # Portal2`). That way it'll be somewhat cleanly and can still be kept sorted alphabetically (which reduces the chance of duplicates sneaking in).

**Comment by fnuecke** [comment]
All right, done. Thanks!

I also used the opportunity to clean up the file a bit. I agree with Vexatos that the two names are too similar to justify keeping both (if that's what he meant, anyway :P). It's for the same reason I 'unified' the two Terminators in my cleanup, for example - I think it's better to keep the list varied over just making it longer.

**Comment by jecowa** [comment]
Those inline comments look really spiffy!

**Pull request merged**
