### PR TITLE
Italian Translation

### PR DESCRIPTION
**Pull request by FrostLee**

### CODE REVIEW

**Comment by fnuecke** [comment]
Awesome, thanks a lot! Could you please squash the commits, though? (`git rebase -i HEAD~6` and then marking your commits as `squash` should do the trick)

**Comment by FrostLee** [comment]
As you can see, I'm quite new at using git. I've tried (and quite succesfully) squashed the commits in just two (one for the translation and one for the robots names: https://github.com/FrostLee/OpenComputers/commit/70a58909701fdbdebe289842b0bd75d7e4be2fe6 and https://github.com/FrostLee/OpenComputers/commit/636809858a33581fa9f8107d15e711d4316cb034) then I'm not sure what happened but while syncing with github the github-windows wonderful program chooses to merge branches (https://github.com/FrostLee/OpenComputers/commit/702455add89662632c335bfc0df8b0b10898e59a)
Of course you cannot reverse merging from github-windows... and I'm not able to do that using the shell.
Now instead of 6 commint the pull request is made of 9 commits...
Can you please help me cleaning the mess I've made?
PS: I've added you @fnuecke as collaborator in my fork, so you should be able to work on that also if you prefer.
PS2: maybe closing this pull request and opening a new one will allow me to avoid all this commits?

**Comment by fnuecke** [comment]
Ah, I have no idea regarding Githubs windows client, sorry. The easiest thing would probably be to create a new fork and just copy your changed files over and commit them in one go, then.

**Comment by FrostLee** [comment]
I'm learning the hard way that the git shell is much better than the github windows client...
Tomorrow I'll create a new fork and make one single commit. Sorry for the mess. ;)
I think we can close this pull request.

**Comment by fnuecke** [comment]
Haha, so I've heard. Thanks for enduring ;-)

**Pull request closed without merging**
