### PR TITLE
Optimized filesystem.name() / Fix filesystem.copy()

### PR DESCRIPTION
**Pull request by SDPhantom**
There is no need to split and run path parsing. Just grab the substring at the end.
Also added argument checking.

### CODE REVIEW

**Comment by SDPhantom** [comment]
Added in a fix for the error return values when filesystem.copy() is unable to open either input or output file.

**Comment by payonel** [comment]
The regex doesn't work when the path is ".", the expected name is nil
other expected results:
./ is nil
../ is nil
.. is nil
a/d/.. is a
a/. is a
./. is nil
./../a./. is a

the file.copy failure for input and output is a good fix.

**Comment by SDPhantom** [comment]
> filesystem.name(path: string): string
Returns the file name component of a path to a file, i.e. everything after the last slash in the canonical form of the specified path.

Aren't those expectations the reverse of the documented effect?

**Comment by SDPhantom** [comment]
I see I need to work a little more on it, though I'll have to do some testing on the way segments() walks through the path. I have ideas on improving it using gsub().

**Comment by payonel** [comment]
for crying out loud
this was the wrong branch

**Pull request merged**
