### PR TITLE
Yet another OPPM update

### PR DESCRIPTION
**Pull request by Vexatos**
Hopefully this fixes dependency installation problems. I need some testers! :expressionless:

### CODE REVIEW

**Comment by fnuecke** [comment]
Who doesn't :-P

**Comment by LordFokas** [comment]
We need automatic tests. Someone needs to invent MineUnit, a JUnit extension for forge mods.
I actually have been thinking about this a lot lately, but I don't have the skills or knowledge to put such thing together :p

**Comment by fnuecke** [comment]
Yeah, something to automatically run MC and emulate players for automated testing would be amazing, tho probably a pain to program (unless some form of "recording" is provided, where you do the test actions once, then save that as a "macro" or something).

**Comment by Vexatos** [comment]
MCMacro incoming.
Some proper OC emulator would be highly sufficient for this, though.

**Comment by LordFokas** [comment]
but but... MineUnit. All the Minecraft. :|

**Comment by Vexatos** [comment]
@LordFokas If you want, please do it :3

**Comment by LordFokas** [comment]
@Vexatos from my previous comment: "(...) but I don't have the skills or knowledge to put such thing together :p"

That basically sums it up :|

**Comment by Vexatos** [comment]
You still can try to do it.

**Pull request merged**
