### PR TITLE
Update df.lua

### PR DESCRIPTION
**Pull request by istasi**
http://istasi.dk/df.png

old versus new

### CODE REVIEW

**Comment by fnuecke** [comment]
As it turned out that tabulate isn't really as versatile as we'd need it to be, could you revert the second commit?

**Comment by istasi** [comment]
Im not home until Sunday late sadly, being without computer and shit :-( .. Will do then I suppose

**Comment by fnuecke** [comment]
Sure, no hurry. Have a nice weekend!

**Comment by istasi** [comment]
reversed

**Pull request merged**
