### PR TITLE
Given a smaller buffer to output

### PR DESCRIPTION
**Pull request by RyanSquared**
I accidentally tried to write 15KB of text to the terminal. This would at least somewhat fix it.

### CODE REVIEW

**Comment by fnuecke** [comment]
Hmm, the problem I see with that, is that it can break unicode chars apart. It's also just fighting the symptoms at a very high level.

It'd probably be better to have the term split output apart using unicode.sub before calling whatever hangs (probably text.detab or text.wrap used in term.write). Also fighting symptoms (that being that the matching reimplemented in Lua - to avoid evil patterns locking down a worker thread - is quite slow), but slightly more generic.

**Comment by dgelessus** [comment]
As for incomplete UTF-8 sequences:
1. Use `utf8.charpattern` to ensure that the last char is valid UTF-8.
2. Not all files are text, and not all stdout is the screen. There are cases where splitting UTF-8 sequences doesn't matter, or where the data is not UTF-8 text.

**Comment by fnuecke** [comment]
1. `utf8` is only available in 5.3 though.
2. So you agree it'd be best to handle this in the term/text libs, since they are meant to display/work with text?

**Comment by dgelessus** [comment]
1. The charpattern is just a normal string, there should be no issue with something like this:

``` lua
local charpattern = utf8 and utf8.charpattern or "..."
```
1. I don't think this is something `term` could handle alone - what should it do when it gets half a UTF-8 sequence? Wait for the next string? And what happens with invalid UTF-8?

**Comment by fnuecke** [comment]
1. Eh, sure. But I don't quite see the desire to manually check that when there's `unicode.len` anyway.
2. I think it'd be fair to expect callers of `term.write` not to pass corrupt strings in.

(Woah. `0.` is auto numeration. TIL)

**Comment by RyanSquared** [comment]
We could read everything up to the last character (something like `:match("^(.-)<CHARPATTERN>$")`) and then have the next read append to that?

**Comment by RyanSquared** [comment]
I think the major problem with this, especially with `cat`, is that it tried to read() too much. Is there any kind of error handling now for this?

**Comment by fnuecke** [comment]
@payonel will the reworked cat also have this problem / has your rework of OpenOS touched buffers to possibly fix it?

**Comment by payonel** [comment]
essentially no, there are no yields added that would resolve this by my rework

**Comment by payonel** [comment]
I'll fix this with another update to term to check uptime and sleep on long writes.

**Pull request closed without merging**
