### PR TITLE
Added hologram projection offset

### PR DESCRIPTION
**Pull request by ingie**
Apologies if this is all wrong, forgive my first ever PR :) 

anyway, as described in issue #546 

hopefully this all follows your standards, i was a bit unsure of the var name length for the additional setting, but i thought i'd keep it wordy and clear, than short and possibly obscure.   

hope you approve,
cheers!
ingie.

### CODE REVIEW

**Comment by ingie** [comment]
derp: i note that i left the default offset in common/TE/Hologram.scala at 1.5 which is cool for me, but not best for others... it should be zero of course.

**Comment by fnuecke** [comment]
Looks pretty good! One thing though: you're not saving the offset - see `write/readFromNBT`, so when saving, quitting and loading again, the offset would be reset. And while you add that, also add the offset to the NBT tag in `write/readFromNBTForClient` to properly synchronize it to clients when the chunk with the hologram projector in it is first sent to them.

You can make changes to your RP by simply committing to the same branch again, btw ;-) (when you're done, please squash your commits into one, though - if you don't know how to, google it, you'll find tons of tutorials).

**Comment by ingie** [comment]
ah... re: NBT: of course - i admit i got excited when it "worked" :)

i'll do that. 

as a separate thing, i'm also working on a 3d primitive library for plotting line vectors + rotation transformation... basically i want to rotate cubes in 3d hologram space - i've done this many years ago in flash, so i'm revising my actionscript and converting it to lua initially... my thinking is it'd be nice to be able to say hologram.line( vec1, vec2 )  / hologram.rotate( thetaX, thetaY, thetaZ ) / hologram.transform( vec ) - you get the idea :)

any thoughts on that?

**Comment by ingie** [comment]
@fnuecke i think i've successfully pushed that NBT/zero the default change, and squashed it properly... i hope - it looks ok on my repo now, so i'm guessing it's all good. 

i'm still hacking this in vi, since i've still yet to set up my dev env properly :) 

but i've released the jar to my own server and it's saving the offset correctly and all that jazz... 

fun script to test with it: 
while true do 
  for i = 0,math.pi*2,math.pi/20 do hologram.setOffset( math.sin(i) + 1.5 ) os.sleep(0.125) end 
end 
... bouncy bouncy :)

**Comment by ingie** [comment]
... i think i've found a slight display bug. i think it's a "feature" of what was there before in the culling - but it's difficult to see normally... basically, if one looks above the hologram to a certain amount, then the hologram isn't rendered.  

this is happening normally - i.e. before i changed it, but i can see that it only happens just on the cusp of not being able to see it anyway in the camera, so it's not noticable. 

on a hunch, i'm thinking i need to factor the offset into the sx/sy/sz culling equation/decision - but i'm not 100% sure of what that bit is specifically doing...

it's not a _bad_ bug, but it's a bug... so i'll look at that when i can... if you have any quick ideas on that, let me know [ not asking to be walked through it at all, just in case you recognise the bug enough to say whether i'm on a wild goose chase/ or on the mark with my own hunch ]

**Comment by fnuecke** [comment]
Ah right, I wanted to mention that earlier but forgot while reading through the diff: you'll want to adjust the bounding box of the tile entity. That is offset the AABB returned from `getRenderBoundingBox` (and/or overscale slightly).

**Comment by ingie** [comment]
gotcha. cheers. i'll do that tomorrow sometime... i'm going to play for a bit, now my holo-projection room is darker :) 

p.s. while i'm on - did you see my post on mcf about the OC website not sending me a confirmation, so i can't post there. i'm still not getting one [ and as said, my email addy and all are correct, and it's not being spammed, so ]

**Comment by ingie** [comment]
... fixed that bug, thanks for that pointer - twas obvious once i saw what that was doing.
I'll still push that tomorrow tho... rather than be too eager again and find other things :)

**Comment by fnuecke** [comment]
Cool. As for the forum account, I activated it manually (and just saw another PM on the MCF from someone with the same issue... will have to keep an eye on that).

**Comment by fnuecke** [comment]
Oh, I only just read your post on the issue to this and realized this is for the 1.7 stable branch.
Please re-create this PR for the `master` branch, since that's the dev branch and my porting workflow is to do everything in 1.6 first, then pull into the 1.7 branch. Flipping that now would be massive headache I think. Thanks!

**Comment by ingie** [comment]
will do... makes sense... the main reason i did it in there is that i couldn't build the gradle from the master due to missing dependencies... so i assumed it wasn't the real master, as it were... 

i'll have a look more into why that was... i just skipped the idea at the time because of that, and worked in a branch i could compile off the bat...

**Comment by fnuecke** [comment]
Hmm, maybe it was just bad timing and some server hosting the dependencies was down (had some builds on Jenkins fail because of that, so annoying).

**Comment by Wuerfel21** [comment]
why doesnt it use offline versions of the dependancy as a fallback anyway?

**Comment by ingie** [comment]
@Wuerfel21 well, it would, but the gradle has to download them at least once before they can be offline :)

**Comment by fnuecke** [comment]
That, too, although I assume he means the Jenkins, in which case the answer is: because I run a clean before each build since I had issues with lingering compiled classes causing problems in the past.

**Comment by ingie** [comment]
righty... it _did_ download everything and build this time [ well, once i'd increased permgen for gradle, but that was a different matter ]

i'll get that back in the correct branch asap... i'm doing a music production session at home today so i doubt i'll get chance until tomorrow.

**Comment by fnuecke** [comment]
Ah, cool. No hurry :)

**Pull request closed without merging**
