### PR TITLE
Updated datacard, correct misspelling

### PR DESCRIPTION
**Pull request by cyber01**
Updated datacard, same as other multilevel items and correct misspelling

### CODE REVIEW

**Comment by fnuecke** [comment]
Thanks! But squash it, please.

**Comment by cyber01** [comment]
Sorry, but how?

**Comment by makkarpov** [comment]
Using `git rebase -i` and `git push -f`

**Comment by makkarpov** [comment]
Especially for your case, try this command sequence (but backup repo first, or maybe try on separate clone):
1. `git rebase -i dd46e54cbd60e1b0af9ed0917543dc0ab6224332`
2. Replace all `pick` with `squash` with exception of first commit - keep `pick` mode there.
2. `git push --force`

**Comment by cyber01** [comment]
It seems to be made :)

**Comment by makkarpov** [comment]
No. When you squash, multiple commits becomes single commit. And repo will not allow you to push squashed data unless you specify `--force`

**Comment by cyber01** [comment]
D:\OpenComputers>git rebase -i dd46e54cbd60e1b0af9ed0917543dc0ab6224332
Successfully rebased and updated refs/heads/RU_doc.
git.exe push -v  --force --progress  "origin" RU_doc
Success

**Comment by makkarpov** [comment]
But commits are still in place. Something is wrong. Did `rebase -i` shown you an interactive text editor?

**Comment by cyber01** [comment]
Before http://puu.sh/jcp1G/691b3dfeaa.png
After http://puu.sh/jcp56/50959919f5.png
Right?

**Comment by cyber01** [comment]
It seems to be made :) №2.
Sorry for delay, i made it first time :)

**Comment by fnuecke** [comment]
Thanks :)

**Pull request merged**
