### PR TITLE
Add and Change some zh-CN.lang translations.

### PR DESCRIPTION
**Pull request by FledgeXu**
I add some new translations to the zh-CN.lang.

### CODE REVIEW

**Comment by loveyanbei** [comment]
你这个汉化，嗯，不太给力。

**Comment by FledgeXu** [comment]
反正还要自己慢慢改。。花了一个下午做出来的。。话说这里用中文不太合适吧。。。

**Comment by FledgeXu** [comment]
Actually it not finished yet,Please do not merge.

**Comment by fnuecke** [comment]
How does this relate to #2402, should one be merged after the other, does this replace it?

**Comment by fnuecke** [comment]
Allright then. In that case, merged the other one. Feel free to rebase this one onto that with additional changes/fixes!

**Pull request closed without merging**
