### PR TITLE
Update robot.names

### PR DESCRIPTION
**Pull request by XeonSquared**
Added names from games by Christine Love, fun stuff.
- Emilia
- Hyun-ae
- Mute

Hopefully they're sorted properly.

### CODE REVIEW

**Comment by skyem123** [comment]
You missed the \* in front of their names.

**Comment by XeonSquared** [comment]
Would that freak out the name system?

**Comment by skyem123** [comment]
I hope not / don't think so.

**Comment by XeonSquared** [comment]
I guess we'll see Sangar's verdict.

**Comment by evieluvsrainbows** [comment]
@shadowkatstudios The *'s are not needed actually.

**Comment by evieluvsrainbows** [comment]
@shadowkatstudios Also, please squash your commits. @fnuecke likes commits being squashed if the PR is a small feature such as this.

**Comment by skyem123** [comment]
@KamranMackey The *'s are part of the story.

**Comment by evieluvsrainbows** [comment]
@skyem123 Not really. They aren't needed at all.

**Comment by evieluvsrainbows** [comment]
@skyem123 Also, the file is supposed to be consistent I believe. Having *'s in the file will make the file inconsistent.

**Comment by dgelessus** [comment]
@KamranMackey The asterisks are part of the names. http://en.wikipedia.org/wiki/Digital:_A_Love_Story#Plot

**Comment by evieluvsrainbows** [comment]
@dgelessus Seriously? Dude, the names in robot.names don't have to be perfect. And look at the damn file. NONE of the names have asterisks in them. And it should stay that way.

**Comment by fnuecke** [comment]
I had already merged the original PR, so I added the stars while cleaning up the list in general.

**Pull request closed without merging**
