### PR TITLE
JUST DIE NIGGER

### PR DESCRIPTION
**Pull request by AKAZARATUSTRA**
JUST DIE NIGGER

### CODE REVIEW

**Comment by Dream-Master** [comment]
@fnuecke please block this troll. He post muliple pots in my GTNH repo as well.
Thanks

**Comment by Dream-Master** [comment]
@payonel

**Comment by LizzyTrickster** [comment]
Have reported them to github.

**Comment by fnuecke** [comment]
Blocked and reported.

**Pull request closed without merging**
