### PR TITLE
Small fix to the error output

### PR DESCRIPTION
**Pull request by ReTeYeZ**
I wouldn't mind to add a small GUI but I thought this is how most programs are executed. I actually made it like this to prevent confusion. Maybe it's a bit easier to understand after this fix. Just tell me what you think.

### CODE REVIEW

**Comment by fnuecke** [comment]
Ah, while it'd probably make sense to adjust the 'usage' info to mirror the format of the other programs, that's not what I actually meant, I was referring to a little 'readme' alike [the one that comes with `dig`](https://github.com/MightyPirates/OpenComputers/blob/master/src/main/resources/assets/opencomputers/loot/TheDig/dig.man) and is present [for most built-in programs](https://github.com/MightyPirates/OpenComputers/tree/master/src/main/resources/assets/opencomputers/loot/OpenOS/usr/man).

**Comment by ReTeYeZ** [comment]
Ok I hope this will do it for now.
I'll later take a look at the other programs how it's implemented there.

Feel free to bother me again if it's not clear enough.

**Comment by ReTeYeZ** [comment]
Those are 'arguments' not 'parameters' right? xD
Not sure about that. If so can you pls change that?

**Comment by ReTeYeZ** [comment]
Just checked the dig.man(and others). Are they accessable ingame? Or are they more of a manual for the GitHub users to get more in-depth knowledge of how a code works?

edit:
Finaly found the edit button^^

**Comment by fnuecke** [comment]
Yeah, it's accessible ingame. The ones in /usr/man directly via `man x` or `help x` (e.g. `man ls`), the ones on disk via `man/dig` when the working directory is that disk (i.e. `cd /mnt/2af` followed by `man dig` would work, assuming the dig disk is mounted at /mnt/2af).

**Comment by ReTeYeZ** [comment]
Ah didn't knew that. Ok I'm on it

**Pull request merged**
