### PR TITLE
Update and improve Chinese translations

### PR DESCRIPTION
**Pull request by Low-power**
* Add some new translated messages
 * Fix some incorrect translations
 * Fix many Simplified Chinese to Traditional Chinese convertion issues

### CODE REVIEW

**Review by papadave66 — COMMENTED** [review]
LGTM

**Comment by asiekierka** [comment]
@3TUSK Could you have a look?

**Comment by 3TUSK** [comment]
I could take a look; however, be ready with possible delay - a lot of things happen concurrently on me right now.

**Comment by asiekierka** [comment]
https://github.com/MightyPirates/OpenComputers/commit/08c16ea1181219c1808cfcfe4de97e09f63e429b

There's also this. These two should probably be combined and compared.

**Pull request merged**
