### PR TITLE
Updated Gradle to 2.3.

### PR DESCRIPTION
**Pull request by evieluvsrainbows**
Minor change, but I upgraded the Gradle version in the `gradle-wrapper.properties` file.

### CODE REVIEW

**Comment by fnuecke** [comment]
Thanks, will test if it breaks things when I find the time :P (because the last time I updated Gradle it did >_>)

**Comment by evieluvsrainbows** [comment]
@fnuecke It shouldn't break anything, since the Travis CI build passed. :smile:

**Comment by fnuecke** [comment]
Let's see what my Jenkins thinks :P
Edit: looking good, phew.

**Comment by evieluvsrainbows** [comment]
@fnuecke Gradle 2.2 & 2.3 don't break anything, so I knew it would work on your Jenkins. :smiley:

**Pull request merged**
