### PR TITLE
Update irc.lua

### PR DESCRIPTION
**Pull request by LizzyTrickster**
Should add in support for /me commands; untested though because for some reason i only do things in places where i cannot test them ¬_¬

### CODE REVIEW

**Comment by rmellema** [comment]
Then you can write it and test it at home, right? :P

**Comment by fnuecke** [comment]
Thanks! Wouldn't this be better if it were `:sub(1, 4) == "/me "`, though, to avoid stuff like `/mehsomerandomtext do stuff` also triggering (mind the gap). Also, is this tested, yet? :P

**Comment by LizzyTrickster** [comment]
It was tested some though it only shows up as "ACTION" in irc, tried using
both \x01 (what my irc bot uses) and \001 (some other ctcp stuff in the irc
program use that)

On 24 April 2014 12:29, Florian Nücke notifications@github.com wrote:

> Thanks! Wouldn't this be better if it were :sub(1, 4) == "/me ", though,
> to avoid stuff like /mehsomerandomtext do stuff also triggering (mind the
> gap). Also, is this tested, yet? :P
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MightyPirates/OpenComputers/pull/229#issuecomment-41269547
> .

## 

Josh Green
My Github https://github.com/TAJG

**Comment by LizzyTrickster** [comment]
ahh, derp. lemme go fix that

**Comment by fnuecke** [comment]
Thanks! :)

**Comment by LizzyTrickster** [comment]
No problemo

**Comment by Techokami** [comment]
Ah, good job on beating me to it. I was working on the same thing yesterday, but didn't get very far as the command wasn't documented in the official IRC docs... :P 
Now I can just update my fork and work instead on adding beep notifications to IRC. You know, user highlights and private messages. Either that or look into making some man pages.

**Comment by fnuecke** [comment]
@Techokami, In case you didn't keep track of the audio issue: computer.bell is now called computer.beep, just to save you from some potential trouble.

**Comment by Techokami** [comment]
Yeah, just saw it now as I was waking up. Thanks for the heads up!

Sent from my Windows Phone

**Pull request merged**
