### PR TITLE
Adding french translation for assets/opencomputers/doc

### PR DESCRIPTION
**Pull request by Pyeroh**
I'm still working on it, so there might be a lot of commits to come, but when I'm done, I'll squash them =)

### CODE REVIEW

**Comment by fnuecke** [comment]
Awesome, lemme know when you're done!

**Comment by Pyeroh** [comment]
Jokes in documentation are a bit hard to reproduce in french, therefore some of them are let in english, some are "translated", and some others are in english but modified, to be more understandable by french people.

**Comment by Pyeroh** [comment]
One question : in items/index.md, for the debug card, there's "(aka AMI)". What do you mean by "AMI" ? Advanced Metering Infrastructure, or American Megatrends ?

**Comment by Fingercomp** [comment]
Adventure Map Interface from Immibis' Peripherals, an advanced computer-controlled "command block".

**Comment by Pyeroh** [comment]
Et voilà !!! Translation is finished :D

**Comment by fnuecke** [comment]
Awesome, thanks a bunch :-) Had to re-save a bunch of the files without the BOM, because the pages rendered stuff like the cedi broken, hopefully that won't now break in the standalone builds :X

**Pull request merged**
