### PR TITLE
Better scrollwheel handling in edit.lua

### PR DESCRIPTION
**Pull request by SDPhantom**
Now scrolls the screen up/down instead of jumping the cursor a bunch of lines.
This tries to preserve cursor position if it's still on screen.

### CODE REVIEW

**Comment by payonel** [comment]
this looks like a good approach. i'd like to test/play with it first. i'm on vacation without a mouse -- will review next week

**Comment by SDPhantom** [comment]
There is an issue that I foresee with it and that has to do with X-scrolling snapping back and forth as you're scrolling lines. It's not easy to counter unless we overhaul how scrolling works and allow direct manipulation of scrolling instead of having to jump the cursor around in order to proc a redraw of the screen.

Ideally, I'd like the cursor to keep its position in the buffer even if it's scrolled offscreen. From there, you can click to change the cursor position as usual or the scrolling will snap back to the cursor when you start typing. Much like a real text editor.

**Comment by SDPhantom** [comment]
The newer commit should handle half of the issue I explained earlier. Due to imitations with the term library, I have to have the scroll code drag the cursor with it when it reaches the edge of the screen.

Previously I moved the cursor one line above or below the screen to force a redraw and at that time, the cursor X position was set to 1. Now I have a similar GPU copy method to **setCursor()** handle scrolling and shift the cursor Y position (relative to the buffer) if would have been moved off screen. This may still cause the X scroll to snap to the left if the line the cursor moves to isn't long enough. At the very least, there won't be the rare occasion where it would snap to the left when scrolling occurs and back to the right when the cursor position is attempted to be restored.

**Comment by SDPhantom** [comment]
Oops, didn't mean to hit close :P

**Comment by payonel** [comment]
in an upcoming update, i'm replacing edit. I'll review this improvement in that version

**Pull request closed without merging**
