### PR TITLE
Fix ProjectRed dep and make hollow covers close on cables.

### PR DESCRIPTION
**Pull request by Kubuxu**
It looks like this:
Hollow covers

### CODE REVIEW

**Comment by Kubuxu** [comment]
Hmm, it is building on my machine.

**Comment by makkarpov** [comment]
The issue of Travis build is that ProjectRed Maven domain is `files.projectredwiki.com`, not `projectredwiki.com` anymore.

**Comment by Kubuxu** [comment]
It is changed. PR requires CoFHCore which is cached on my machine.
Fixing it now.

**Comment by Kubuxu** [comment]
Might have fixed that, I have to wait for Travis build as cache won't allow to check me on my machine.

**Comment by fnuecke** [comment]
Thanks!

**Pull request merged**
