### PR TITLE
Update sh.lua

### PR DESCRIPTION
**Pull request by istasi**
Keep dem quotes that text.tokenize so happy destroy!

### CODE REVIEW

**Comment by istasi** [comment]
#412

**Comment by fnuecke** [comment]
No, tokenize _should_ remove the quotes. They're syntax. To pass quotes, encase them in the other type of quotes, e.g. `text.tokenize([[this is a 'multi-word token "with" quotes']])`.

**Comment by istasi** [comment]
grep "function tabIt" df.lua 

This kind of syntax is just not possible currently, because the program being callable does not receive the actually argument supplied but rather a parsed/stripped version of the same.

But why not give the arguments as supplied?

**Comment by fnuecke** [comment]
What do you mean by 'not possible'? In that example `grep` would get two arguments, `function tabIt` and `df.lua`, which should be perfectly fine?

And passing the arguments 'as-is' (including quotes) will in _almost all cases_ force the programs to post-process the arguments themselves, stripping the quotes.

Lastly, this is like stuff is handled in C (at least on Linux), too:

```
pi@spiffy cat test.c
#include <stdio.h>
int main(int argc, const char** argv) {
  while (argc-- > 0)
    printf("%s\n", argv[argc]);
  return 0;
}
pi@spiffy ~ $ gcc test.c -o test
pi@spiffy ~ $ ./test "quoted argument" normal arguments
arguments
normal
quoted argument
./test
```

**Pull request closed without merging**
