### PR TITLE
Made Hover Boots dyeable.

### PR DESCRIPTION
**Pull request by Vexatos**
I know it's not the prettiest Scala code the world has ever seen, but it should suffice.

Allows dyeing hover boots akin to Leather Armor. Crafting with a water bucket allows removing the dye again.
Most of the code is taken from [AsieLib](https://github.com/asiekierka/AsieLib) and it works quite well.

### CODE REVIEW

**Comment by SoniEx2** [comment]
Can I undye on a cauldron?

**Comment by Vexatos** [comment]
Now you can.

**Comment by SoniEx2** [comment]
Right-click on cauldron, like vanilla leather armor?

**Comment by Vexatos** [comment]
No, that's boring.

**Comment by SoniEx2** [comment]
But UX!

**Comment by Vexatos** [comment]
Tossing is quite an experience, if you ask me.

**Comment by SoniEx2** [comment]
But consistency!

**Comment by fnuecke** [comment]
Thanks, this is neat!

**Pull request merged**
