### PR TITLE
[1.6] Fixed rack power crash

### LINKED ISSUE #1546: [1.6] Rack energy crash
When attempting to feed energy to rack the game crashes with following stack trace:

```
java.lang.ClassCastException: li.cil.oc.server.network.Network$NodeBuilder$$anon$4 cannot be cast to li.cil.oc.api.network.Connector
    at li.cil.oc.common.tileentity.Rack.connector(Rack.scala:211)
    at li.cil.oc.common.tileentity.traits.power.Common$class.tryChangeBuffer(Common.scala:51)
    at li.cil.oc.common.tileentity.Rack.tryChangeBuffer(Rack.scala:40)
    at li.cil.oc.common.tileentity.traits.power.RedstoneFlux$class.receiveEnergy(RedstoneFlux.scala:17)
    at li.cil.oc.common.tileentity.Rack.receiveEnergy(Rack.scala:40)
    at mods.eln.simplenode.energyconverter.EnergyConverterElnToOtherFireWallRf.updateEntity(EnergyConverterElnToOtherFireWallRf.java:19)
    at mods.eln.simplenode.energyconverter.EnergyConverterElnToOtherEntity.func_145845_h(EnergyConverterElnToOtherEntity.java:235)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at fastcraft.c.p.a(F:19)
    at fastcraft.Hooks.aq(F:153)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

This happened when using electrical age cable and Immersive engineering cell

### PR DESCRIPTION
**Pull request by magik6k**
Basically fixes #1546

### CODE REVIEW

**Comment by fnuecke** [comment]
Thanks! Why the new trait, instead of just overriding `createNode` in `Rack`, though?

**Comment by magik6k** [comment]
Just thought something may use it too in the future.

**Comment by magik6k** [comment]
I may fix creative server power in a bit, so I guess wait a sec with merging this.

**Comment by fnuecke** [comment]
Hrm, I suppose. Could still be out when the time comes, but I'll leave the decision to you then.
And sure, will wait for the creative power fix, thanks :)

**Comment by magik6k** [comment]
Done, I guess. Now also fixes #1547.

**Comment by fnuecke** [comment]
My OCD demands I point out the collapsed imports and the missing space between the if and the opening brace :x

(I can't remember the exact scenario, but I remember getting annoyed by star(/underscore)-imports while keeping things in sync between different MC versions, since then I avoid them.)

**Comment by magik6k** [comment]
OK, I got rid of ._ import and squashed the commits

**Comment by fnuecke** [comment]
But the space! :P Oh well, nevermind, the next autoformat will catch it.

Thanks again!

**Comment by magik6k** [comment]
Ah, that space ;p

**Pull request merged**
