### PR TITLE
Add password-protected debug cards

### PR DESCRIPTION
**Pull request by makkarpov**
- Config property `enableDebugCard` was renamed to `debugCardAccess` (does not renames value in existing configs yet)
- `true` and `false` are treated like before - completely enables/disables debug card. String values are treated as a password that must be passed to `debug.unlock(string)` to enable all other debug card functions.

Change is intended for servers where people may cheat in items but admins need debug card.

### CODE REVIEW

**Comment by fnuecke** [comment]
Interesting idea. I'll look over it when I can.

One idea to ponder though: I'm not super-keen on actually security-relevant passwords in-game. Maybe prefer having a whitelist of players (name or UUID) and require the machine to only have registered users in that whitelist (but at least one). To get that list, `context.asInstanceOf[Machine].users` should work, I think (better as a match to avoid errors when it doesn't, but in principle).

**Comment by makkarpov** [comment]
1) You write malicious program that use debug card
2) You write script that adds admins using `computer` API and runs program

All conditions are fulfilled - only admins are registered for this computer, but you have malicious script running on it. You do not have access to this computer anymore, but you have access to debug card and can, for example, listen network for incoming commands and execute them.

---

Another approach is to somehow _activate_ debug card with shift-rightclicking by admin with card in hand. But with this approach it's hard to revoke already activated cards. (But it can be integrated into existing password system - right-clicking by admin will fill in correct password into the debug card state)

**Comment by fnuecke** [comment]
Ah, fair point, that'd work.

I like the idea of using the binding system. Basically allow using bound debug cards, if the owner is in the whitelist. Though losing such a card would be an issue, true. If we could make that somewhat less problematic, I'd really like this approach.

**Comment by makkarpov** [comment]
To revoke bound cards we can attach some `nonce` field to each whitelist entry, so card is active only if owner is whitelisted and nonce matches. So revoking a card == changing a nonce for specific user. But it will require some other file than config.

**Comment by makkarpov** [comment]
Will rework and create separate PR for new code.

**Pull request closed without merging**
