### PR TITLE
Readded Project Red support

### PR DESCRIPTION
**Pull request by brisingraerowing**
Simply readds Project Red support. Also slightly reformats build.gradle to line things up (that was annoying my OCD).

### CODE REVIEW

**Comment by asiekierka** [comment]
LGTM

**Comment by asiekierka** [comment]
Pertains to https://github.com/MightyPirates/OpenComputers/issues/2847

**Comment by brisingraerowing** [comment]
It appears that the AE2 maven dep line is incorrect now. Should I fix that

**Comment by brisingraerowing** [comment]
Closed in error.

**Comment by payonel** [comment]
i merged this manually (and locally) (and tested it) and pushed the code back up. Thanks for getting this started @BrisingrAerowing

**Comment by payonel** [comment]
ff08a5ce562c0f41202d4e2fec711c14987f6b20

**Comment by tnekohue** [comment]
Found an off by one issue when passing a table
image

**Pull request closed without merging**
