### PR TITLE
Chinese font for font.hex supplement [对font.hex进行中文补充]

### PR DESCRIPTION
**Pull request by xiaoye97**
Using the SIL License Font "Source Han Seri" to Supplement the font.hex File for Chinese Fonts. Replaced 0x4E00-0x9FBF and 0xFF01-0xFF65, Others use the default funscii settings.
[使用SIL许可证字体“思源宋体”补充font.hex。只替换了0x4E00-0x9FBF 和 0xFF01-0xFF65 区域，其他都使用funscii的默认设置]

### CODE REVIEW

**Comment by xiaoye97** [comment]
Sorry for an extension of two days, I was the first time to use github, just learned how to use pull requests.

**Comment by payonel** [comment]
Thanks for your hard work. I'll review these changes and merge them when time allows

**Comment by asiekierka** [comment]
I'm not sure I'm fine with this. The font we use for the Japanese language is actually pixel-handcrafted; this one is exported from a vectorized one and I'm not sure how good it looks; do you have a screenshot?

**Comment by payonel** [comment]
i have requested a 3rd party review the font, but they've been busy and haven't voted in support or not of this merge. I'll keep this ticket open for further discussion, but removing it from the milestone

**Comment by payonel** [comment]
new fonts
new_set1
new_set2

olds fonts
old_set1
old_set2

**Comment by r888800009** [comment]
I think the new fonts are not clear enough.

for example, The Chinese characters are not clear to read.:
 **営嘎嗅嗇
 國圍圈園圓圖團圜**
image

**Comment by asiekierka** [comment]
The old font was hand-made, but it was made primarily for Japanese language home computer use and applied by me to the parts of Unicode it covered. I could not find a liberally licensed pixel-drawn equivalent for Chinese or Korean, however.

**Comment by payonel** [comment]
closing old PR - the fonts were blurry, and not hand crafted.

**Pull request closed without merging**
