### PR TITLE
The most important fix in the history of this mod.

### PR DESCRIPTION
**Pull request by Vexatos**
Unacceptable!

### CODE REVIEW

**Comment by fnuecke** [comment]
No, in some cases it needed to be UTF-8 to show up correctly, in some CP-1252 or whatever, this is good enough.

**Comment by gjgfuj** [comment]
Wait, are you saying ü isn't utf-8? Unicode text format 8? ???. Do you mean
ASCII?

**Comment by skyem123** [comment]
In Minecraft, it would render the ü in a different font to the rest of the text.

**Comment by dgelessus** [comment]
@skyem123 No, I think most Latin characters with diacritics (`üùúû` etc.) are displayed in the default Minecraft font.

@gjgfuj I think he means that some things decode the text as Latin-1 or Windows-1252 instead of UTF-8, which would mess up the Ã¼.

**Comment by fnuecke** [comment]
What @dgelessus said. I know that in some cases MC decoded it one way and in others the other (though I'm not 100% sure what the cases were, i.e. whether it was built on Jenkins vs. local or Windows vs. Linux and so on). Either way, it's something I can't be bothered with anymore >_>

**Comment by dgelessus** [comment]
This is a JSON file, right? In that case you could use `\u00fc` in place of `ü`.

**Pull request closed without merging**
