### PR TITLE
Add Rotarycraft Integration (item stack converters for jetpacks and …

### PR DESCRIPTION
**Pull request by Voidi**
…springpowered pumps)

### CODE REVIEW

**Comment by fnuecke** [comment]
Looking good, will test soon (probably tomorrow), thanks!

I'm assuming you're using `GameRegistry.findItem` because RC doesn't have a more specific way of looking up items in it its own API?

**Comment by Voidi** [comment]
Have you updated the API? Last time i was looking it was still the old version with Powerthings only.
And for the pump item there is no API anyway.

**Comment by fnuecke** [comment]
I haven't had a look at all, was just wondering blindly ^^

**Comment by fnuecke** [comment]
Thanks; feel free to give the next dev build with this in it a shot, to make sure it still works :)

**Pull request merged**
