### PR TITLE
term wrapping and sh tab completion fixes

### PR DESCRIPTION
**Pull request by payonel**
term wrapping fixes
Backspacing or deleting during vertical wrap would not update the current end of line correctly what the text was being pulled from the next line

horizontal wrapping deletion was not using dx,dy and instead was removing text from absolute positions on the screen

horizontal wrapping was pushing spaces beyond the windowed areas

### CODE REVIEW

**Comment by payonel** [comment]
closes https://github.com/MightyPirates/OpenComputers/issues/1671

**Comment by payonel** [comment]
The third commit is also important. Found some regressions while writing some samples for Kodos on how to use term. The commit message says more.

**Comment by payonel** [comment]
Turns out the broken tab complete is NOT a regression in this PR, but has been around the whole time with my new term library. It's a bit of a timing issue, but basically, key-up events are clearing the hint cache (dumb!)

Also, I tested lua prompt to have (for examples) "sides" in env all the way back to before my openos overhaul code, and it was still missing. I'll check further back ( 1.5 days ) but for now, this PR seems healthy with the tab complete fix.

**Comment by payonel** [comment]
ok mr sangar
I tested ALL the way back, from the very beginning of /bin/lua's support for tab completion. It did not have a full environment with things such as sides. Sorry :(

**Comment by fnuecke** [comment]
Ohh, thanks a lot for looking into that then. Old and unnoticed bugs are the best bugs I guess >_>
Nevermind that for now then, I suppose. Will re-test and merge in the evening!

**Pull request merged**
