### PR TITLE
VBO hologram renderer

### PR DESCRIPTION
**Pull request by evg-zhabotinsky**
I finally did it.
Render code totally rewritten. Fps is much better.
Line in PacketHandler.scala is removed because rescaling no longer requires recompilation.
~~Also, consider doing something with d99bc5815c680198dfa7cd94eede40e5b4e66296 because it causes synchronous hologram updates every 2 seconds which causes freezes.~~ solved

### CODE REVIEW

**Comment by Vexatos** [comment]
Don't tell me I'll be able to use Hologram projectors with more than 0.2 FPS :o
Thank you!

**Comment by evg-zhabotinsky** [comment]
Well, if you have 0.2 FPS now I'm afraid it's not going to help a lot. It will be faster but still unplayable.

**Comment by evg-zhabotinsky** [comment]
Now this issue #259 is almost irrelevant on my machine. No lag if I am not looking at ~10 simultaneously updating checkerboard holograms. So I guess it should be playable on older hardware now.

**Comment by fnuecke** [comment]
Wow, this is amazing! Thanks so much for working on this :)

I had a look at it, and what I am noticing is that there's no 'lighting' at all - right now the faces are lit slightly differently (like normal blocks) to get a better feeling for the hologram's depth. In your implementation it's completely 'flat'. Which is probably because you don't set any normals in the VBO, yes? Could you add those?

Current:

Patched:

**Comment by evg-zhabotinsky** [comment]
Hmm I explicitly turned lighting off and commented on it (line 250):
`GL11.glDisable(GL11.GL_LIGHTING) // Hologram that reflects light... It would be awesome! But...`
Well, it really looks better with lighting no matter how realistic it is.
~~**UPD** Looks like tesselator does all the lighting in Minecraft and I'll have to emulate it's behavior.~~
**UPD2** Looked through decompiled tesselator code. It does nothing special to normals. ~~I do not understand why lighting does not work in my code.~~
**UPD3** Okay. How obvious is that glScale also scales normals? They are just directions after all!

**Comment by fnuecke** [comment]
Brilliant! I'm looking through it right now :)

**Comment by fnuecke** [comment]
And it's in. Again, thanks a lot!

**Pull request merged**
