### PR TITLE
Grammar + Format

### PR DESCRIPTION
**Pull request by megamandos**
Minor grammar and format fixes for the English version of the manual.

### CODE REVIEW

**Comment by megamandos** [comment]
Ah, when you look at it in-game, the "d" is on the next line. So it looked really weird. I'll fix this, give me a sec.

**Comment by megamandos** [comment]
Fixed, the "bugger" is not intentional, right?

**Comment by dgelessus** [comment]
> Fixed, the "bugger" is not intentional, right?

Yes, that's clearly a typo. ;)

> Ah, when you look at it in-game, the "d" is on the next line.

@fnuecke sounds like a bug, text shouldn't linewrap at a formatting change.

**Comment by fnuecke** [comment]
Eh, the thing with the going to a new line is unfortunate indeed; adding a forced newline before it will be needed. It's not really a bug, since the formatting changes it's actually intended to allow the renderer to wrap there (fwiw, Github's Markdown rendering also would wrap that), e.g.
.....................................................................................................................................................`require`d.
^ The d is wrapped there for me, no space between the two. Anyway, adding a manual newline should solve this. If you'd like you could add that, then please squash the commits and I'll merge it.

**Comment by megamandos** [comment]
Fixed and squashed.

**Comment by fnuecke** [comment]
Thanks!

**Pull request merged**
