### PR TITLE
Update ls.lua

### PR DESCRIPTION
**Pull request by istasi**
columns!, also doesn't break when max width adds up with resolution, thingy thingy

### CODE REVIEW

**Comment by istasi** [comment]
this is a rather ugly solution, sigh .... but works -.-'

**Comment by fnuecke** [comment]
Hmm, some ideas for improving this:
- check if `gpu` is available, if it isn't just don't format.
- use the primary gpu (if available), not the first one in the list.
- use text.padRight.

For the first one, alternatively it might make sense to check if `io.output() == io.stdout`? E.g. to avoid formatting stuff when it's piped (in besh e.g., given someone/I find(s) the time to fix it...)

**Comment by istasi** [comment]
Changed so newlines only are inserted if io.output() == io.stdout and component.gpu isn't nil, or enough files to reach math.huge

it still formats width between file entries based on max length though, regardless of whenever there's an gpu or not though...

Though in which case would ls ever be used where there's no gpu?, and in said case, why not just use filesystem.list directly?

**Comment by fnuecke** [comment]
Looking over it now.

As for no GPU: servers where all IO is redirected through some pseudo-SSH thing, I guess?

**Pull request merged**
