### PR TITLE
Ic2 crop integration

### PR DESCRIPTION
**Pull request by repo-alt**

### CODE REVIEW

**Comment by repo-alt** [comment]
Commit history is a bit weird due to merging from different forks, but it can be squashed w/o any problems.

**Comment by Nex4rius** [comment]
If I understand this correctly the geolyzer could read ic2 crop data?
SOUNDS AWESOME

Next we need a robot program for automated crop breeding :)

**Comment by payonel** [comment]
thanks for updating your code. it looks great but i need to run it first. will update tonight

**Comment by repo-alt** [comment]
Huh, I already forgot I proposed that change upstream :)
This would definitely need squashing, quite a bit of unnecessary history there.

**Comment by repo-alt** [comment]
(Will rebase and make clean PR)

**Pull request closed without merging**
