### PR TITLE
Made ls display amount of dirs/files

### PR DESCRIPTION
**Pull request by Wuerfel21**
Self explanatory

### CODE REVIEW

**Comment by fnuecke** [comment]
a) Directories, not Directorys.
b) Why?
c) Does 'normal' ls ever do this? Is it a flag? If so, make it one. Otherwise, I'm not a fan :P

**Comment by bendem** [comment]
`ls` is just a list of names on columns. The difference is visible if you do `ls -p` because it adds a trailing `/` to directories: https://gist.github.com/bendem/29b02230c90b9681b14b

**Comment by Wuerfel21** [comment]
@fnuecke a)english is not my native language, and it was late in the night when i wrote this
b)if you have many files in a folder a d you want to know how many they are, currently you need to count them yourself c) i havent messed around with linux that much, so i cant talk about it, but why have an exact copy? Btw, dos did it,

**Comment by Kubuxu** [comment]
Because whole OS is made similar to Linux/Unix and it is natural environment for some people.
`ls` was designed for parsing its output that why it they wanted to add something they added parameter to activate it.

**Comment by Wuerfel21** [comment]
Made it by option

**Comment by bendem** [comment]
It should still be "directories" and not "directorys" :)

**Pull request merged**
