### PR TITLE
patch-1

### PR DESCRIPTION
**Pull request by Starlii10**
okay I may have messed up the description-

### CODE REVIEW

**Comment by asiekierka** [comment]
Thank you!

**Comment by Starlii10** [comment]
...can you tell I don't understand PRs and forks?

**Comment by asiekierka** [comment]
A *fork* is a copy of the repository which links back to the original; you can think of it as a "parent-child" relationship.

A *pull request* is a request filed to one of the repository's forks (or the original - they're all copies of the same repository, after all) for them to integrate your changes with their repository.

**Comment by Starlii10** [comment]
I got jumpscared after I made the PR. If I had looked in the top left, I would have clearly seen "MightyPirates" instead of "WiseDragoon5374". I didn't know branch-1 was being merged into the actual repo.

TL:DR, double check your PR before submitting it. I learned that the hard way.

🤦

**Comment by asiekierka** [comment]
I mean, you made a valid contribution! Congratulations!

**Pull request merged**
