### PR TITLE
Add Florian's nanomachine program into OpenOS - Program may need some cleanup

### PR DESCRIPTION
**Pull request by MFernflower**
.

### CODE REVIEW

**Comment by gjgfuj** [comment]
It should really just be in oppm imo. Definitely not worth going into
openos.

**Comment by MFernflower** [comment]
Well, I will just leave this here for the appropriate people to merge it into openos/oppm or wherever this may need to go.

**Comment by gjgfuj** [comment]
Well, for one thing sangar /is/ Florian. So you've submitted his own code
to him. Have fun.

**Comment by MFernflower** [comment]
I was just gonna ask if he would add his own program to openos - Also methinks other people work on OC

**Comment by MFernflower** [comment]
Forget it

**Comment by fnuecke** [comment]
I guess I could add it to OPPM. I'll do it in the evening if I remember to.

**Pull request closed without merging**
